name: Azure Storage Account Provisioning

on:
  workflow_dispatch:
    inputs:
      sa_name:
        description: 'Storage Account Name'
        required: true
      sa_location:
        description: 'Azure Location'
        required: true
      sa_account_tier:
        description: 'Account Tier'
        required: true
      sa_account_replication_type:
        description: 'Replication Type'
        required: true
      #sa_rgname:
        #description: 'Resource Group Name'
        #required: true
      action:
        description: 'Terraform Action'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set Azure Service Principal credentials as environment variables
      - name: Set Azure Service Principal Environment Variables
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: echo "Azure credentials set"

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
      - name: Debug Input1
        run: echo "${{ inputs.action }}"

      - name: Run Terraform
        run: |
          terraform ${{ inputs.action }} -auto-approve \
          -var="sa_name=${{ github.event.inputs.sa_name }}" \
          -var="sa_location=${{ github.event.inputs.sa_location }}" \
          -var="sa_account_tier=${{ github.event.inputs.sa_account_tier }}" \
          -var="sa_account_replication_type=${{ github.event.inputs.sa_account_replication_type }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
# -var="sa_rgname=${{ github.event.inputs.sa_rgname }}" #Default value is set in the variables.tf
